apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: krgeobuk-cicd

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - pvc.yaml
  - configmap-plugins.yaml
  - configmap-casc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
