apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: krgeobuk-devops

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - pvc.yaml
  - configmap-plugins.yaml
  - configmap-casc.yaml
  - deployment.yaml
  - service.yaml
  # Ingress: 환경에 맞게 둘 중 하나만 활성화
  - ingress-dev.yaml    # dev:  http://jenkins.192.168.0.28.nip.io
  # - ingress.yaml      # prod: https://jenkins.krgeobuk.com
