# Verdaccio 패키지 스토리지 영구 볼륨
# @krgeobuk/* 패키지 파일 저장
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verdaccio-storage-pvc
  namespace: krgeobuk-cicd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
# Verdaccio conf 디렉토리 영구 볼륨
# htpasswd (유저 계정) 저장 - Verdaccio가 직접 쓰기 필요
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verdaccio-conf-pvc
  namespace: krgeobuk-cicd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
